const BASE = "https://raw.githubusercontent.com/Tarikul-Islam-Anik/Telegram-Animated-Emojis/main"

export interface TelegramEmoji {
  name: string
  src: string
}

export interface EmojiCategory {
  id: string
  label: string
  icon: string // native emoji used as tab icon
  emojis: TelegramEmoji[]
}

function toEmojis(category: string, names: string[]): TelegramEmoji[] {
  return names.map((name) => ({
    name,
    src: `${BASE}/${encodeURIComponent(category)}/${encodeURIComponent(name)}.webp`,
  }))
}

export const emojiCategories: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "\u{1F600}",
    emojis: toEmojis("Smileys", [
      "Grinning Face",
      "Grinning Face With Big Eyes",
      "Grinning Face With Smiling Eyes",
      "Beaming Face With Smiling Eyes",
      "Grinning Squinting Face",
      "Grinning Face With Sweat",
      "Rolling On The Floor Laughing",
      "Face With Tears Of Joy",
      "Slightly Smiling Face",
      "Upside Down Face",
      "Melting Face",
      "Winking Face",
      "Smiling Face With Smiling Eyes",
      "Smiling Face With Halo",
      "Smiling Face With Hearts",
      "Smiling Face With Heart Eyes",
      "Star Struck",
      "Face Blowing A Kiss",
      "Kissing Face",
      "Kissing Face With Closed Eyes",
      "Smiling Face With Tear",
      "Smiling Face",
      "Face Savoring Food",
      "Face With Tongue",
      "Squinting Face With Tongue",
      "Winking Face With Tongue",
      "Zany Face",
      "Money Mouth Face",
      "Hugging Face",
      "Shushing Face",
      "Thinking Face",
      "Saluting Face",
      "Zipper Mouth Face",
      "Face With Raised Eyebrow",
      "Neutral Face",
      "Expressionless Face",
      "Face Without Mouth",
      "Dotted Line Face",
      "Face In Clouds",
      "Smirking Face",
      "Unamused Face",
      "Face With Rolling Eyes",
      "Grimacing Face",
      "Face Exhaling",
      "Lying Face",
      "Smiling Face With Sunglasses",
      "Disguised Face",
      "Nerd Face",
      "Face With Monocle",
      "Confused Face",
      "Slightly Frowning Face",
      "Frowning Face",
      "Frowning Face With Open Mouth",
      "Worried Face",
      "Face With Open Mouth",
      "Hushed Face",
      "Astonished Face",
      "Flushed Face",
      "Pleading Face",
      "Face Holding Back Tears",
      "Face With Peeking Eye",
      "Anguished Face",
      "Fearful Face",
      "Anxious Face With Sweat",
      "Sad But Relieved Face",
      "Crying Face",
      "Loudly Crying Face",
      "Face Screaming In Fear",
      "Confounded Face",
      "Persevering Face",
      "Disappointed Face",
      "Downcast Face With Sweat",
      "Weary Face",
      "Tired Face",
      "Yawning Face",
      "Face With Steam From Nose",
      "Angry Face",
      "Pouting Face",
      "Angry Face With Horns",
      "Smiling Face With Horns",
      "Face With Symbols On Mouth",
      "Exploding Head",
      "Face With Head Bandage",
      "Face With Thermometer",
      "Nauseated Face",
      "Face Vomiting",
      "Sneezing Face",
      "Hot Face",
      "Cold Face",
      "Woozy Face",
      "Face With Spiral Eyes",
      "Dizzy Face",
      "Face With Diagonal Mouth",
      "Face With Medical Mask",
      "Partying Face",
      "Drooling Face",
      "Sleepy Face",
      "Sleeping Face",
      "Relieved Face",
      "Pensive Face",
      "Cowboy Hat Face",
      "Clown Face",
      "Face With Open Eyes And Hand Over Mouth",
      "Face With Hand Over Mouth",
      "Cat With Tears Of Joy",
      "Cat With Wry Smile",
      "Grinning Cat",
      "Grinning Cat With Smiling Eyes",
      "Smiling Cat With Heart Eyes",
      "Kissing Cat",
      "Crying Cat",
      "Weary Cat",
      "Pouting Cat",
      "See No Evil Monkey",
      "Hear No Evil Monkey",
      "Speak No Evil Monkey",
      "Ghost",
      "Alien",
      "Alien Monster",
      "Robot",
      "Skull",
      "Skull And Crossbones",
      "Pile Of Poo",
      "Goblin",
      "Ogre",
    ]),
  },
  {
    id: "people",
    label: "People",
    icon: "\u{1F44B}",
    emojis: toEmojis("People", [
      "Waving Hand",
      "Raised Hand",
      "Hand With Fingers Splayed",
      "Raised Back Of Hand",
      "Victory Hand",
      "Crossed Fingers",
      "Love You Gesture",
      "Sign Of The Horns",
      "Call Me Hand",
      "Backhand Index Pointing Left",
      "Backhand Index Pointing Right",
      "Backhand Index Pointing Up",
      "Backhand Index Pointing Down",
      "Index Pointing Up",
      "Index Pointing At The Viewer",
      "Thumbs Up",
      "Thumbs Down",
      "Raised Fist",
      "Oncoming Fist",
      "Left Facing Fist",
      "Right Facing Fist",
      "Clapping Hands",
      "Raising Hands",
      "Open Hands",
      "Palms Up Together",
      "Handshake",
      "Folded Hands",
      "Heart Hands",
      "Writing Hand",
      "Nail Polish",
      "Ok Hand",
      "Pinched Fingers",
      "Pinching Hand",
      "Flexed Biceps",
      "Middle Finger",
      "Palm Down Hand",
      "Palm Up Hand",
      "Leftwards Hand",
      "Rightwards Hand",
      "Hand With Index Finger And Thumb Crossed",
      "Vulcan Salute",
      "Person Shrugging",
      "Person Facepalming",
      "Man Shrugging",
      "Woman Shrugging",
      "Man Facepalming",
      "Woman Facepalming",
      "Man Dancing",
      "Woman Dancing",
      "Baby",
      "Santa Claus",
      "Mrs Claus",
      "Mx Claus",
      "Technologist",
      "Man Technologist",
      "Woman Technologist",
      "Man Teacher",
      "Man Health Worker",
      "Woman Health Worker",
      "Man Police Officer",
      "Woman Police Officer",
      "Vampire",
      "Man Vampire",
      "Woman Vampire",
      "Zombie",
      "Man Zombie",
      "Woman Zombie",
      "Old Woman",
      "Pregnant Woman",
      "People Hugging",
      "Speaking Head",
      "Bust In Silhouette",
      "Busts In Silhouette",
      "Family Man Woman Girl Boy",
      "Eyes",
      "Ear",
      "Ear With Hearing Aid",
      "Nose",
      "Mouth",
      "Tongue",
      "Tooth",
      "Bone",
      "Foot",
      "Leg",
      "Footprints",
      "Biting Lip",
      "Mechanical Arm",
      "Mechanical Leg",
    ]),
  },
  {
    id: "animals",
    label: "Animals & Nature",
    icon: "\u{1F43E}",
    emojis: toEmojis("Animals and Nature", [
      "Dog Face",
      "Cat Face",
      "Cat",
      "Black Cat",
      "Mouse Face",
      "Hamster",
      "Rabbit Face",
      "Rabbit",
      "Fox",
      "Bear",
      "Polar Bear",
      "Koala",
      "Panda",
      "Tiger Face",
      "Tiger",
      "Lion",
      "Leopard",
      "Horse Face",
      "Horse",
      "Unicorn",
      "Zebra",
      "Deer",
      "Giraffe",
      "Gorilla",
      "Monkey Face",
      "Cow",
      "Ox",
      "Pig Face",
      "Pig Nose",
      "Frog",
      "Kangaroo",
      "Llama",
      "Raccoon",
      "Hedgehog",
      "Bison",
      "Seal",
      "Chicken",
      "Turkey",
      "Hatching Chick",
      "Baby Chick",
      "Front Facing Baby Chick",
      "Bird",
      "Penguin",
      "Dove",
      "Flamingo",
      "Swan",
      "Parrot",
      "Duck",
      "Owl",
      "Bat",
      "Fish",
      "Tropical Fish",
      "Octopus",
      "Squid",
      "Lobster",
      "Shrimp",
      "Spouting Whale",
      "Snake",
      "Turtle",
      "T Rex",
      "Sauropod",
      "Ant",
      "Honeybee",
      "Lady Beetle",
      "Beetle",
      "Butterfly",
      "Bug",
      "Cricket",
      "Cockroach",
      "Mosquito",
      "Microbe",
      "Spider",
      "Spider Web",
      "Snail",
      "Paw Prints",
      "Rose",
      "Tulip",
      "Cherry Blossom",
      "Blossom",
      "Hibiscus",
      "Bouquet",
      "Rosette",
      "Four Leaf Clover",
      "Shamrock",
      "Herb",
      "Seedling",
      "Cactus",
      "Palm Tree",
      "Deciduous Tree",
      "Evergreen Tree",
      "Fire",
      "High Voltage",
      "Rainbow",
      "Star",
      "Glowing Star",
      "Snowflake",
      "Snowman",
      "Snowman Without Snow",
      "Sun",
      "Sun With Face",
      "Sun Behind Cloud",
      "Sun Behind Small Cloud",
      "Sun Behind Large Cloud",
      "Sun Behind Rain Cloud",
      "Cloud",
      "Cloud With Rain",
      "Cloud With Snow",
      "Cloud With Lightning",
      "Cloud With Lightning And Rain",
      "Full Moon",
      "Full Moon Face",
      "New Moon",
      "New Moon Face",
      "First Quarter Moon",
      "First Quarter Moon Face",
      "Last Quarter Moon",
      "Last Quarter Moon Face",
      "Waxing Crescent Moon",
      "Waxing Gibbous Moon",
      "Waning Crescent Moon",
    ]),
  },
  {
    id: "food",
    label: "Food & Drink",
    icon: "\u{1F354}",
    emojis: toEmojis("Food and Drink", [
      "Hamburger",
      "Pizza",
      "Hot Dog",
      "French Fries",
      "Taco",
      "Sandwich",
      "Stuffed Flatbread",
      "Pretzel",
      "Meat On Bone",
      "Poultry Leg",
      "Pancakes",
      "Cooking",
      "Bento Box",
      "Rice Ball",
      "Rice Cracker",
      "Sushi",
      "Oden",
      "Dango",
      "Fish Cake With Swirl",
      "Banana",
      "Strawberry",
      "Chocolate Bar",
      "Cookie",
      "Birthday Cake",
      "Shortcake",
      "Cupcake",
      "Pie",
      "Doughnut",
      "Custard",
      "Lollipop",
      "Popcorn",
      "Soft Ice Cream",
      "Hot Beverage",
      "Bubble Tea",
      "Glass Of Milk",
      "Baby Bottle",
      "Cup With Straw",
      "Tropical Drink",
      "Cocktail Glass",
      "Wine Glass",
      "Tumbler Glass",
      "Clinking Glasses",
      "Bottle With Popping Cork",
      "Beverage Box",
      "Mate",
      "Canned Food",
      "Pouring Liquid",
      "Fork And Knife With Plate",
    ]),
  },
  {
    id: "activity",
    label: "Activity",
    icon: "\u{1F3C6}",
    emojis: toEmojis("Activity", [
      "Trophy",
      "1st Place Medal",
      "2nd Place Medal",
      "3rd Place Medal",
      "Sports Medal",
      "Military Medal",
      "Soccer Ball",
      "Basketball",
      "Video Game",
      "Artist Palette",
      "Performing Arts",
      "Crystal Ball",
      "Magic Wand",
      "Sparkles",
      "Balloon",
      "Party Popper",
      "Confetti Ball",
      "Firecracker",
      "Fireworks",
      "Sparkler",
      "Christmas Tree",
      "Jack O Lantern",
      "Mirror Ball",
      "Ticket",
      "Admission Tickets",
    ]),
  },
  {
    id: "travel",
    label: "Travel & Places",
    icon: "\u{1F680}",
    emojis: toEmojis("Travel and Places", [
      "Rocket",
      "Airplane",
      "Automobile",
      "Taxi",
      "Police Car",
      "Ambulance",
      "Locomotive",
      "Motor Boat",
      "Beach With Umbrella",
      "Camping",
      "Desert Island",
      "Classical Building",
      "House",
      "Roller Coaster",
      "Hot Springs",
      "Compass",
      "Moai",
    ]),
  },
  {
    id: "objects",
    label: "Objects",
    icon: "\u{1F4A1}",
    emojis: toEmojis("Objects", [
      "Light Bulb",
      "Laptop",
      "Keyboard",
      "Mobile Phone",
      "Mobile Phone With Arrow",
      "Telephone",
      "Telephone Receiver",
      "Television",
      "Microphone",
      "Studio Microphone",
      "Megaphone",
      "Crown",
      "Top Hat",
      "Graduation Cap",
      "Gem Stone",
      "Key",
      "Old Key",
      "Locked With Key",
      "Money Bag",
      "Money With Wings",
      "Coin",
      "Briefcase",
      "Handbag",
      "Purse",
      "Shopping Bags",
      "Shopping Cart",
      "Luggage",
      "High Heeled Shoe",
      "Books",
      "Open Book",
      "Memo",
      "Pencil",
      "Newspaper",
      "Musical Note",
      "Musical Notes",
      "Bomb",
      "Magnifying Glass Tilted Left",
      "Magnifying Glass Tilted Right",
      "Microscope",
      "Telescope",
      "Pill",
      "Syringe",
      "Stethoscope",
      "Test Tube",
      "Thermometer",
      "Toolbox",
      "Military Helmet",
      "Hourglass Done",
      "Hourglass Not Done",
      "Bar Chart",
      "Chart Increasing",
      "Chart Decreasing",
      "Abacus",
      "Identification Card",
      "Ballot Box With Ballot",
      "Card Index Dividers",
      "File Folder",
      "Inbox Tray",
      "Outbox Tray",
      "Incoming Envelope",
      "Tear Off Calendar",
      "Printer",
      "Clapper Board",
      "Coffin",
      "Reminder Ribbon",
      "Roll Of Paper",
      "Soap",
      "Sponge",
    ]),
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "\u{2764}\u{FE0F}",
    emojis: toEmojis("Symbols", [
      "Red Heart",
      "Orange Heart",
      "Yellow Heart",
      "Green Heart",
      "Blue Heart",
      "Purple Heart",
      "Black Heart",
      "White Heart",
      "Brown Heart",
      "Heart On Fire",
      "Mending Heart",
      "Broken Heart",
      "Two Hearts",
      "Revolving Hearts",
      "Beating Heart",
      "Growing Heart",
      "Sparkling Heart",
      "Heart With Arrow",
      "Heart With Ribbon",
      "Heart Decoration",
      "Heart Exclamation",
      "Love Letter",
      "Kiss Mark",
      "Hundred Points",
      "Anger Symbol",
      "Collision",
      "Dizzy",
      "Speech Balloon",
      "Thought Balloon",
      "Right Anger Bubble",
      "Zzz",
      "Check Mark",
      "Check Mark Button",
      "Check Box With Check",
      "Cross Mark",
      "Exclamation Mark",
      "Double Exclamation Mark",
      "Exclamation Question Mark",
      "White Exclamation Mark",
      "Question Mark",
      "White Question Mark",
      "Cool Button",
      "Free Button",
      "New Button",
      "Ok Button",
      "Up Button",
      "Top Arrow",
      "Currency Exchange",
      "Customs",
      "Baggage Claim",
      "Left Luggage",
      "Passport Control",
      "Mens Room",
      "Womens Room",
      "Baby Symbol",
      "No One Under Eighteen",
      "Aquarius",
      "Aries",
      "Cancer",
      "Capricorn",
      "Gemini",
      "Leo",
      "Libra",
      "Ophiuchus",
      "Pisces",
      "Sagittarius",
      "Scorpio",
      "Taurus",
      "Virgo",
    ]),
  },
  {
    id: "flags",
    label: "Flags",
    icon: "\u{1F3F4}",
    emojis: toEmojis("Flags", [
      "Chequered Flag",
      "Triangular Flag",
      "Black Flag",
      "White Flag",
      "Pirate Flag",
      "Flag United States",
      "Flag United Kingdom",
      "Flag France",
      "Flag Germany",
      "Flag Japan",
      "Flag South Korea",
      "Flag China",
      "Flag India",
      "Flag Brazil",
      "Flag Russia",
      "Flag Spain",
      "Flag Italy",
      "Flag Argentina",
      "Flag Armenia",
      "Flag Austria",
      "Flag Bahamas",
      "Flag Belarus",
      "Flag Belgium",
      "Flag Benin",
      "Flag Bulgaria",
      "Flag Burkina Faso",
      "Flag Cameroon",
      "Flag Chad",
      "Flag Cote Divoire",
      "Flag Croatia",
      "Flag Czechia",
      "Flag Djibouti",
      "Flag Equatorial Guinea",
      "Flag Estonia",
      "Flag Gabon",
      "Flag Ghana",
      "Flag Guinea",
      "Flag Guinea Bissau",
      "Flag Hungary",
      "Flag Indonesia",
      "Flag Ireland",
      "Flag Jordan",
      "Flag Lithuania",
      "Flag Luxembourg",
      "Flag Madagascar",
      "Flag Mali",
      "Flag Monaco",
      "Flag Morocco",
      "Flag Mozambique",
      "Flag Myanmar Burma",
      "Flag Netherlands",
      "Flag Nigeria",
      "Flag Palestinian Territories",
      "Flag Peru",
      "Flag Philippines",
      "Flag Poland",
      "Flag Romania",
      "Flag Sao Tome Principe",
      "Flag Saudi Arabia",
      "Flag Senegal",
      "Flag Sierra Leone",
      "Flag Singapore",
      "Flag Sint Maarten",
      "Flag Somalia",
      "Flag South Sudan",
      "Flag Sudan",
      "Flag Ukraine",
      "Flag United Arab Emirates",
      "Flag Uzbekistan",
      "Flag Vietnam",
      "Flag Western Sahara",
      "Flag Yemen",
    ]),
  },
]
