export interface TelegramEmoji {
  name: string
  char: string
  src?: never
}

export interface EmojiCategory {
  id: string
  label: string
  icon: string
  emojis: TelegramEmoji[]
}

function e(name: string, char: string): TelegramEmoji {
  return { name, char }
}

export const emojiCategories: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "😀",
    emojis: [
      e("Grinning Face", "😀"),
      e("Big Eyes", "😃"),
      e("Smiling Eyes", "😄"),
      e("Beaming", "😁"),
      e("Laughing", "😆"),
      e("Sweat Smile", "😅"),
      e("Rolling Floor Laughing", "🤣"),
      e("Tears of Joy", "😂"),
      e("Slightly Smiling", "🙂"),
      e("Upside Down", "🙃"),
      e("Winking", "😉"),
      e("Smiling Heart Eyes", "😍"),
      e("Star Struck", "🤩"),
      e("Kissing", "😘"),
      e("Smiling Tear", "🥲"),
      e("Savoring Food", "😋"),
      e("Tongue Out", "😛"),
      e("Winking Tongue", "😜"),
      e("Zany", "🤪"),
      e("Money Mouth", "🤑"),
      e("Hugging", "🤗"),
      e("Shushing", "🤫"),
      e("Thinking", "🤔"),
      e("Saluting", "🫡"),
      e("Zipper Mouth", "🤐"),
      e("Melting", "🫠"),
      e("Halo", "😇"),
      e("Hearts", "🥰"),
      e("Sunglasses", "😎"),
      e("Nerd", "🤓"),
    ],
  },
  {
    id: "gestures",
    label: "Gestures",
    icon: "👋",
    emojis: [
      e("Wave", "👋"),
      e("Raised Hand", "✋"),
      e("High Five", "🤚"),
      e("OK", "👌"),
      e("Pinched Fingers", "🤌"),
      e("Victory", "✌️"),
      e("Crossed Fingers", "🤞"),
      e("Love You Gesture", "🤟"),
      e("Thumbs Up", "👍"),
      e("Thumbs Down", "👎"),
      e("Clap", "👏"),
      e("Raising Hands", "🙌"),
      e("Folded Hands", "🙏"),
      e("Point Up", "☝️"),
      e("Point Down", "👇"),
      e("Point Left", "👈"),
      e("Point Right", "👉"),
      e("Fist", "✊"),
      e("Handshake", "🤝"),
      e("Writing Hand", "✍️"),
      e("Nail Polish", "💅"),
      e("Flexed Bicep", "💪"),
    ],
  },
  {
    id: "hearts",
    label: "Hearts",
    icon: "❤️",
    emojis: [
      e("Red Heart", "❤️"),
      e("Orange Heart", "🧡"),
      e("Yellow Heart", "💛"),
      e("Green Heart", "💚"),
      e("Blue Heart", "💙"),
      e("Purple Heart", "💜"),
      e("Brown Heart", "🤎"),
      e("Black Heart", "🖤"),
      e("White Heart", "🤍"),
      e("Broken Heart", "💔"),
      e("Heart on Fire", "❤️‍🔥"),
      e("Mending Heart", "❤️‍🩹"),
      e("Sparkling Heart", "💖"),
      e("Growing Heart", "💗"),
      e("Beating Heart", "💓"),
      e("Revolving Hearts", "💞"),
      e("Heart Exclamation", "❣️"),
      e("Heart Decoration", "💟"),
      e("Two Hearts", "💕"),
      e("Heart Eyes", "😍"),
      e("Heart Kiss", "😘"),
    ],
  },
  {
    id: "people",
    label: "People",
    icon: "👤",
    emojis: [
      e("Person", "🧑"),
      e("Man", "👨"),
      e("Woman", "👩"),
      e("Baby", "👶"),
      e("Boy", "👦"),
      e("Girl", "👧"),
      e("Old Man", "👴"),
      e("Old Woman", "👵"),
      e("Family", "👨‍👩‍👧‍👦"),
      e("Couple", "👫"),
      e("Doctor", "🧑‍⚕️"),
      e("Teacher", "🧑‍🏫"),
      e("Farmer", "🧑‍🌾"),
      e("Cook", "🧑‍🍳"),
      e("Mechanic", "🧑‍🔧"),
      e("Artist", "🧑‍🎨"),
      e("Pilot", "🧑‍✈️"),
      e("Astronaut", "🧑‍🚀"),
      e("Firefighter", "🧑‍🚒"),
      e("Superhero", "🦸"),
      e("Zombie", "🧟"),
    ],
  },
  {
    id: "nature",
    label: "Nature",
    icon: "🌿",
    emojis: [
      e("Dog", "🐶"),
      e("Cat", "🐱"),
      e("Lion", "🦁"),
      e("Tiger", "🐯"),
      e("Bear", "🐻"),
      e("Panda", "🐼"),
      e("Fox", "🦊"),
      e("Wolf", "🐺"),
      e("Monkey", "🐵"),
      e("Elephant", "🐘"),
      e("Giraffe", "🦒"),
      e("Zebra", "🦓"),
      e("Horse", "🐴"),
      e("Unicorn", "🦄"),
      e("Bee", "🐝"),
      e("Butterfly", "🦋"),
      e("Flower", "🌸"),
      e("Rose", "🌹"),
      e("Sunflower", "🌻"),
      e("Tree", "🌳"),
      e("Fire", "🔥"),
      e("Wave", "🌊"),
      e("Rainbow", "🌈"),
    ],
  },
  {
    id: "food",
    label: "Food",
    icon: "🍕",
    emojis: [
      e("Pizza", "🍕"),
      e("Burger", "🍔"),
      e("Fries", "🍟"),
      e("Hot Dog", "🌭"),
      e("Sandwich", "🥪"),
      e("Taco", "🌮"),
      e("Burrito", "🌯"),
      e("Sushi", "🍣"),
      e("Rice", "🍚"),
      e("Ramen", "🍜"),
      e("Pasta", "🍝"),
      e("Bread", "🍞"),
      e("Cake", "🎂"),
      e("Ice Cream", "🍦"),
      e("Coffee", "☕"),
      e("Tea", "🍵"),
      e("Cocktail", "🍹"),
      e("Beer", "🍺"),
      e("Grape", "🍇"),
      e("Strawberry", "🍓"),
      e("Watermelon", "🍉"),
      e("Pineapple", "🍍"),
    ],
  },
  {
    id: "activities",
    label: "Activities",
    icon: "⚽",
    emojis: [
      e("Soccer", "⚽"),
      e("Basketball", "🏀"),
      e("Football", "🏈"),
      e("Tennis", "🎾"),
      e("Volleyball", "🏐"),
      e("Baseball", "⚾"),
      e("Cricket", "🏏"),
      e("Rugby", "🏉"),
      e("Trophy", "🏆"),
      e("Medal", "🥇"),
      e("Dart", "🎯"),
      e("Guitar", "🎸"),
      e("Piano", "🎹"),
      e("Drum", "🥁"),
      e("Microphone", "🎤"),
      e("Movie", "🎬"),
      e("Game Controller", "🎮"),
      e("Dice", "🎲"),
      e("Paint", "🎨"),
      e("Book", "📚"),
      e("Running", "🏃"),
      e("Swimming", "🏊"),
    ],
  },
  {
    id: "travel",
    label: "Travel",
    icon: "✈️",
    emojis: [
      e("Airplane", "✈️"),
      e("Rocket", "🚀"),
      e("Car", "🚗"),
      e("Bus", "🚌"),
      e("Train", "🚆"),
      e("Bicycle", "🚲"),
      e("Ship", "🚢"),
      e("Helicopter", "🚁"),
      e("Ambulance", "🚑"),
      e("Police Car", "🚔"),
      e("Fire Engine", "🚒"),
      e("Taxi", "🚕"),
      e("Globe", "🌍"),
      e("Map", "🗺️"),
      e("Compass", "🧭"),
      e("Mountain", "⛰️"),
      e("Beach", "🏖️"),
      e("City", "🏙️"),
      e("House", "🏠"),
      e("Office", "🏢"),
      e("Hospital", "🏥"),
      e("Stadium", "🏟️"),
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    emojis: [
      e("Bulb", "💡"),
      e("Money Bag", "💰"),
      e("Credit Card", "💳"),
      e("Phone", "📱"),
      e("Laptop", "💻"),
      e("TV", "📺"),
      e("Camera", "📷"),
      e("Clock", "⏰"),
      e("Gift", "🎁"),
      e("Key", "🔑"),
      e("Lock", "🔒"),
      e("Bomb", "💣"),
      e("Hammer", "🔨"),
      e("Wrench", "🔧"),
      e("Scissors", "✂️"),
      e("Pencil", "✏️"),
      e("Envelope", "✉️"),
      e("Newspaper", "📰"),
      e("Calendar", "📅"),
      e("Chart", "📊"),
      e("Magnifying Glass", "🔍"),
      e("Telescope", "🔭"),
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "💯",
    emojis: [
      e("100", "💯"),
      e("Check Mark", "✅"),
      e("Cross Mark", "❌"),
      e("Warning", "⚠️"),
      e("No Entry", "⛔"),
      e("Prohibited", "🚫"),
      e("Star", "⭐"),
      e("Sparkles", "✨"),
      e("Party Popper", "🎉"),
      e("Confetti", "🎊"),
      e("Question Mark", "❓"),
      e("Exclamation", "❗"),
      e("Up Arrow", "⬆️"),
      e("Down Arrow", "⬇️"),
      e("Left Arrow", "⬅️"),
      e("Right Arrow", "➡️"),
      e("Recycle", "♻️"),
      e("Peace", "☮️"),
      e("Yin Yang", "☯️"),
      e("Om", "🕉️"),
      e("Cross", "✝️"),
      e("Infinity", "♾️"),
    ],
  },
]
